/**
 * Tech governance policy templates for Oblig.
 * Draft bodies map to APAC vendor / TRM / data / AI themes.
 * Not legal advice — customise and have counsel review before external use.
 */

export interface PolicyTemplate {
  id: string;
  title: string;
  type: string;
  desc: string;
  /** Full draft body used when generating a policy document */
  body: string;
}

function shell(opts: {
  purpose: string;
  scope?: string;
  roles: string;
  requirements: string;
  related?: string;
}): string {
  return [
    '1. Purpose',
    opts.purpose,
    '',
    '2. Scope',
    opts.scope ??
      'This policy applies to all employees, contractors, and third parties who design, operate, access, or support company systems, products, or customer data.',
    '',
    '3. Roles and responsibilities',
    opts.roles,
    '',
    '4. Requirements',
    opts.requirements,
    '',
    '5. Related frameworks (reference)',
    opts.related ??
      'Themes commonly tested under APAC technology and vendor risk expectations (e.g. MAS TRM and outsourcing-related instruments, BNM RMiT, and peer market guidance). Confirm the instruments that apply to your buyers and licence class.',
    '',
    '6. Exceptions',
    'Exceptions require written approval from the policy owner and must be time-bound, risk-assessed, and logged.',
    '',
    '7. Review',
    'This policy is reviewed at least annually, after a material incident, or when relevant regulatory guidance changes. Version history is retained with the document.',
    '',
    '—',
    'Draft generated by Oblig for internal editing. Not legal or regulatory advice.',
  ].join('\n');
}

export const POLICY_TEMPLATES: PolicyTemplate[] = [
  {
    id: 'vendor-tprm',
    title: 'Vendor & Third-Party Risk Management Policy',
    type: 'Third-party',
    desc: 'Due diligence, ongoing monitoring, and subcontractor visibility for technology vendors.',
    body: shell({
      purpose:
        'Define how the organisation assesses, onboards, monitors, and exits technology and service vendors so that third-party risk does not undermine confidentiality, integrity, availability, or regulatory expectations of institutional customers.',
      roles:
        'Executive owner: accountable for third-party technology risk.\nProcurement / vendor management: runs due diligence and maintains the vendor inventory.\nSecurity / IT: reviews technical evidence and residual risk.\nLegal: contract clauses (audit rights, security, subcontracting, exit).\nAll staff: do not onboard material vendors outside this process.',
      requirements: [
        '4.1 Maintain an inventory of technology vendors and material outsourcing arrangements, including purpose, data access, and criticality.',
        '4.2 Before onboarding a material vendor, complete documented due diligence proportionate to risk (security evidence, financial/operational fitness, subcontracting model, data location).',
        '4.3 Require written contracts covering security obligations, incident notification, audit/inspection rights where appropriate, data protection, and exit/return or destruction of data.',
        '4.4 Re-assess material vendors on a defined cadence (at least annually for high-criticality arrangements), not only at initial signup.',
        '4.5 Identify concentration risk (over-reliance on a single provider or region) and document mitigating actions or exit options.',
        '4.6 Record residual risk acceptance for any material gaps that remain after due diligence.',
      ].join('\n'),
      related:
        'Aligns with themes in MAS technology risk and outsourcing expectations, BNM RMiT third-party/cloud oversight, and peer APAC vendor questionnaires. Not a substitute for entity-specific notices.',
    }),
  },
  {
    id: 'data-residency',
    title: 'Data Residency & Cross-Border Transfer Policy',
    type: 'Data',
    desc: 'Where customer data lives per market and when it may leave the country.',
    body: shell({
      purpose:
        'State where customer and regulated data is stored and processed, under what conditions cross-border transfer is allowed, and how the organisation answers institutional buyers and market-specific residency rules.',
      roles:
        'Executive owner: approves data-location strategy.\nEngineering / infrastructure: implements residency controls and documents regions.\nSecurity / privacy: assesses transfer mechanisms and residual risk.\nSales / customer success: do not commit to residency terms outside this policy.',
      requirements: [
        '4.1 Maintain a current register of systems that process customer data, with primary and backup regions/countries.',
        '4.2 For each target market, document whether customer data may leave the country and under what contractual or technical conditions.',
        '4.3 Apply stricter controls where hard localisation or in-country expectations apply (e.g. certain Cambodia and Indonesia contexts) — verify current rules before go-live.',
        '4.4 For cloud services, document the shared-responsibility model, encryption/key ownership, and provider regions in use.',
        '4.5 Changes to data location require impact assessment, approval, and customer/contract review where commitments exist.',
        '4.6 Provide a clear, consistent answer pack for vendor questionnaires on data location and cross-border transfer.',
      ].join('\n'),
    }),
  },
  {
    id: 'incident-notification',
    title: 'Incident Notification Policy (Regulator SLAs)',
    type: 'Security',
    desc: 'Roles, severity, and notification paths including market-specific timers.',
    body: shell({
      purpose:
        'Ensure security and technology incidents are detected, classified, contained, and communicated to leadership, affected institutional customers, and — where applicable — regulators within expected timeframes.',
      roles:
        'Incident commander (named role): leads response for severity-1/2 events.\nSecurity / IT: detect, contain, investigate, preserve evidence.\nExecutive sponsor: external communications and regulator escalation decisions.\nLegal / compliance: notification wording and privilege considerations.',
      requirements: [
        '4.1 Maintain a written incident response plan with severity levels, on-call contacts, and escalation paths.',
        '4.2 Classify incidents by impact on confidentiality, integrity, availability, and customer harm.',
        '4.3 For severe incidents affecting regulated customers or reportable systems, follow market-specific notification expectations. Example often cited for Singapore: rapid initial notice for severe impact and a formal root-cause report on a short follow-up timeline — confirm the exact obligations for your entity type and contracts.',
        '4.4 Notify affected institutional customers per contract and this policy; keep a communication log.',
        '4.5 Run at least one tabletop exercise per year; record lessons learned and update the plan.',
        '4.6 After major incidents, complete a root-cause analysis and track corrective actions to closure.',
      ].join('\n'),
    }),
  },
  {
    id: 'ai-governance',
    title: 'AI Governance & Model Risk Policy',
    type: 'AI Governance',
    desc: 'Inventory, human oversight, and lifecycle controls for AI/ML use.',
    body: shell({
      purpose:
        'Govern the development, procurement, deployment, and monitoring of AI/ML systems so that fairness, accountability, transparency, security, and human oversight expectations can be evidenced to leadership and institutional customers.',
      roles:
        'Executive owner: approves high-impact AI use cases.\nProduct / engineering: maintain model inventory and technical controls.\nRisk / compliance: challenge high-impact use and monitor regulatory AI guidance.\nAll staff: do not deploy customer-facing AI outside the approved inventory process.',
      requirements: [
        '4.1 Maintain an inventory of AI/ML systems: purpose, data used, human-in-the-loop design, and whether the system affects customers.',
        '4.2 Classify use cases by impact (e.g. high / medium / low). High-impact uses require explicit approval and enhanced monitoring.',
        '4.3 Apply FEAT-oriented principles (fairness, ethics, accountability, transparency) appropriate to the use case, especially for customer-facing decisions.',
        '4.4 Define human oversight: when a human must review, override, or approve model outputs.',
        '4.5 Cover the lifecycle: development or vendor selection, validation/testing, deployment, monitoring, and retirement.',
        '4.6 Third-party AI (APIs, embedded models) is subject to vendor due diligence under the Vendor & Third-Party Risk Management Policy.',
      ].join('\n'),
      related:
        'Informed by emerging APAC AI-in-finance guidance (e.g. MAS FEAT-oriented discussions, OJK lifecycle-style expectations, and high-impact AI oversight themes in markets such as Korea). Confirm local instruments for your buyers.',
    }),
  },
  {
    id: 'subcontractor',
    title: 'Subcontractor Consent & Outsourcing Register Policy',
    type: 'Third-party',
    desc: 'Sub-processor visibility, consent, and register-ready descriptions.',
    body: shell({
      purpose:
        'Ensure subcontractors and sub-processors that touch customer data or critical systems are identified, controlled, and disclosed so institutional customers can meet their own outsourcing and register obligations.',
      roles:
        'Vendor management: maintains subcontractor list and consent records.\nLegal: contract flow-downs and customer consent language.\nSecurity: assesses subcontractor security posture.\nAccount teams: do not authorise new subcontractors without this process.',
      requirements: [
        '4.1 Maintain a current list of subcontractors/sub-processors that handle customer data or administer critical systems.',
        '4.2 Flow down security, confidentiality, and incident obligations to subcontractors in writing.',
        '4.3 Obtain required customer consent or notice before adding subcontractors where contracts or local frameworks require it (some markets expect prior written consent, not only notification).',
        '4.4 Provide customers, on request, with a clear description of services suitable for an outsourcing or third-party register entry.',
        '4.5 Review the subcontractor list at least annually and on material change.',
      ].join('\n'),
    }),
  },
  {
    id: 'bcp-exit',
    title: 'Business Continuity & Exit Planning Policy',
    type: 'Continuity',
    desc: 'Continuity for critical services and exit/portability for institutional customers.',
    body: shell({
      purpose:
        'Ensure critical technology services can withstand disruption and that institutional customers have a credible exit and data-handover path if the relationship ends.',
      roles:
        'Executive owner: sets continuity priorities.\nIT / operations: implements backup, recovery, and failover testing.\nCustomer success / legal: exit and portability commitments in contracts.',
      requirements: [
        '4.1 Identify critical services and recovery objectives (RTO/RPO) proportionate to customer impact.',
        '4.2 Maintain backup, recovery, and (where required) multi-region or alternate-provider options; test recovery at least annually.',
        '4.3 Document an exit/offboarding process: data export formats, timelines, secure destruction, and knowledge transfer.',
        '4.4 Address concentration risk where a single provider or region could disable critical services.',
        '4.5 Align customer contract language with this policy so exit commitments are deliverable.',
      ].join('\n'),
    }),
  },
  {
    id: 'cloud',
    title: 'Cloud Security & Shared Responsibility Policy',
    type: 'Security',
    desc: 'Cloud posture, shared responsibility, keys, and residency alignment.',
    body: shell({
      purpose:
        'Define how the organisation uses cloud services securely, including shared responsibility, configuration baselines, identity, encryption, and alignment with data residency commitments.',
      roles:
        'Cloud owner (engineering): architecture, hardening, monitoring.\nSecurity: baselines, reviews, and exception handling.\nProcurement: cloud contract and assurance requirements.',
      requirements: [
        '4.1 Document cloud providers, services (IaaS/PaaS/SaaS), regions, and the shared-responsibility boundary for each material workload.',
        '4.2 Enforce identity controls (including MFA for privileged cloud access), least privilege, and logging of administrative actions.',
        '4.3 Define encryption in transit and at rest; document who holds key material and under what conditions keys can be rotated or revoked.',
        '4.4 Apply secure configuration baselines and review high-risk changes before production.',
        '4.5 Align cloud regions and data flows with the Data Residency & Cross-Border Transfer Policy.',
        '4.6 Include cloud providers in vendor due diligence and ongoing monitoring.',
      ].join('\n'),
    }),
  },
  {
    id: 'vuln-pentest',
    title: 'Vulnerability & Penetration Testing Policy',
    type: 'Security',
    desc: 'Patch cadence, vulnerability management, and independent testing.',
    body: shell({
      purpose:
        'Ensure technical vulnerabilities are identified, prioritised, remediated, and independently tested so residual risk stays within appetite and vendor-assurance expectations can be met.',
      roles:
        'Security: owns vulnerability management and external test coordination.\nEngineering: remediates within agreed SLAs.\nExecutive owner: accepts risk for exceptions.',
      requirements: [
        '4.1 Maintain an asset inventory sufficient to prioritise vulnerability scanning and patching.',
        '4.2 Run vulnerability assessment on a defined cadence for internet-facing and critical systems; track remediation SLAs by severity.',
        '4.3 Commission independent penetration testing at least annually for critical systems (or more often when risk or customer contracts require it).',
        '4.4 Track findings to closure; document risk acceptance for any deferred items.',
        '4.5 Retain executive summaries suitable for institutional customer due diligence requests.',
      ].join('\n'),
      related:
        'Independent testing and vulnerability management are recurring themes under BNM RMiT and peer APAC technology risk expectations.',
    }),
  },
  {
    id: 'access-control',
    title: 'Access Control & Privileged Access Policy',
    type: 'Security',
    desc: 'MFA, least privilege, joiner-mover-leaver, and access reviews.',
    body: shell({
      purpose:
        'Control who can access systems and data, with particular discipline for privileged accounts, so unauthorised access risk is reduced and evidence is available for audits and vendor questionnaires.',
      roles:
        'IT / identity owner: implements IAM controls.\nManagers: approve access appropriate to role.\nSecurity: monitors privileged activity and review completion.\nHR / people ops: trigger joiner-mover-leaver updates.',
      requirements: [
        '4.1 Grant access on least-privilege and need-to-know principles; prefer role-based access where feasible.',
        '4.2 Require multi-factor authentication for remote access and for privileged or production-critical systems.',
        '4.3 Control privileged accounts (named owners, vaulting or equivalent, logging, and tighter review cycles).',
        '4.4 Complete joiner-mover-leaver processes promptly, including revocation on termination.',
        '4.5 Review access rights on a defined cadence; remediate excessive access.',
        '4.6 Log and retain authentication and privileged activity per logging standards.',
      ].join('\n'),
    }),
  },
  {
    id: 'board-reporting',
    title: 'Board Risk Reporting & Escalation Policy',
    type: 'Governance',
    desc: 'Risk appetite, ownership, and reporting cadence to leadership.',
    body: shell({
      purpose:
        'Ensure technology, cyber, data, and AI risks are owned, reported, and escalated to senior management or the board on a cadence that supports informed oversight.',
      roles:
        'Board / senior management: set risk appetite and review technology risk regularly.\nTechnology risk owner / CISO-equivalent: prepares reporting and escalates material issues.\nControl owners: provide status on treatments and incidents.',
      requirements: [
        '4.1 Document technology and vendor-risk appetite (or incorporate it into enterprise risk appetite) in writing.',
        '4.2 Name an executive owner for technology risk (and CISO-level ownership where expected by target markets or customers).',
        '4.3 Report technology risk, major incidents, and material third-party issues to leadership at least quarterly, and ad hoc for severe events.',
        '4.4 Track open high risks to remediation or formal acceptance.',
        '4.5 Align reporting content with evidence used in institutional due diligence where relevant.',
      ].join('\n'),
    }),
  },
  {
    id: 'secure-sdlc',
    title: 'Secure Development & Change Management Policy',
    type: 'Security',
    desc: 'Secure SDLC, testing, and controlled production change.',
    body: shell({
      purpose:
        'Build and change software in a controlled way so security defects are reduced before production and changes are traceable for audit and customer assurance.',
      roles:
        'Engineering leadership: owns SDLC standards.\nSecurity: defines control requirements and may gate high-risk releases.\nAll engineers: follow secure coding, review, and change procedures.',
      requirements: [
        '4.1 Document the software development lifecycle including design review, code review, testing, and release approval.',
        '4.2 Apply secure coding practices and dependency hygiene for production services.',
        '4.3 Separate environments (e.g. dev/test/prod); restrict production access.',
        '4.4 Require change records for production changes, with rollback considerations for high-risk changes.',
        '4.5 Include security testing appropriate to risk (SAST/DAST, dependency scanning, or equivalent) before major releases.',
      ].join('\n'),
      related:
        'Secure SDLC and change control are explicit themes in MAS TRM-oriented assessments and many APAC vendor questionnaires.',
    }),
  },
  {
    id: 'logging-monitoring',
    title: 'Logging, Monitoring & Retention Policy',
    type: 'Security',
    desc: 'Security logging, monitoring, and retention baselines.',
    body: shell({
      purpose:
        'Define what security-relevant events are logged, how they are monitored, how long they are retained, and who responds to alerts.',
      roles:
        'Security / SOC owner: monitoring and alert response.\nEngineering: ensure systems emit required logs.\nInfrastructure: retention, integrity, and access to log stores.',
      requirements: [
        '4.1 Identify critical systems and the security events that must be logged (authentication, privileged actions, security control failures, significant data access where feasible).',
        '4.2 Centralise or otherwise protect logs against tampering; restrict access to log data.',
        '4.3 Define retention periods appropriate to risk and customer/regulatory expectations (some markets quote multi-year baselines for certain institutions — confirm what your buyers require).',
        '4.4 Monitor for anomalies and security alerts with defined response ownership.',
        '4.5 Review monitoring coverage when major systems or vendors change.',
      ].join('\n'),
    }),
  },
];

export function getPolicyTemplate(idOrTitle: string): PolicyTemplate | undefined {
  const q = idOrTitle.toLowerCase();
  return POLICY_TEMPLATES.find(
    t => t.id === idOrTitle || t.title.toLowerCase() === q || t.title.toLowerCase().includes(q),
  );
}
